### ISSUE TITLE
Implement bot base with discord-go

### ISSUE THREAD

**Issue by Xeckt** [Xeckt/district#1]
Bot base needs to be implemented using the library `discordgo`

Implementation will need to consist of:

- Standard bot startup
- Basic handlers implemented

**Comment by periaate** [comment]
![image](https://github.com/Xeckt/district/assets/49311112/fdb85e80-131f-4ca4-b512-9d60c3a09542)

Tested functionality on a personal server, although not reproducible, it should be fine for now. @Xeckt
